### ISSUE TITLE
golang UnmarshalBase64() is not compatible with python marshalled file

### ISSUE THREAD

**Issue by rexshang** [EverythingMe/inbloom#6]
golang UnmarshalBase64() would throw an exception while decoding a file marshaled using python.

You can reproduce the issue with the following line:
bloom, err := inbloom.UnmarshalBase64("j+gAZAAAAGQAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAIAAAAAEAAAAAAAAAAAAABAAAAAAAAAYAAAAAAACAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAQAAgAAAAAAAAAAAAAAAAAACBgAA=")

I've experimented changing bloom.go:174 to:
	if b, err := base64.StdEncoding.DecodeString(b64); err != nil {

Using base64.StdEncoding seems to make it work.

**Comment by dvirsky** [comment]
@rexshang if you can create a regression test that fails without the fix and not with it, please just issue a PR and I'll merge it.

**Comment by bergundy** [comment]
@rexshang I took a look.
`UnmarshalBase64()` is a convenience function, that wraps `Unmarshal()` and uses `UrlEncoding` to decode from base64.
The python implementation of inbloom doesn't have base64 convenience functions, to generate base64 with URL encoding in Python use [urlsafe_b64encode](https://docs.python.org/2/library/base64.html#base64.urlsafe_b64encode) instead of `b64encode`.

Going forward we could:
1. Add a golang helper that supports standard base64 encoding (perhaps by adding an optional parameter to `UnmarshalBase64()`.
1. Add a base64 encoder to the python implementation that's compatible with golang `UnmarshalBase64()`.
1. Close this issue.

WDYT?

**Comment by rexshang** [comment]
@bergundy Either 1 or 2 would solve this compatibility issue.

I do see the strength of this package being able to go between different languages.  So my answer really depends on which encoding you want to default on.  If you want to go with standard base64 encoding, then option 1 would work.  Otherwise, option 2 would be preferred.

**Comment by bergundy** [comment]
@rexshang sorry for the late reply, I missed the notification.
Let's add an optional parameter to the golang method.
Do you want to submit a PR with a fix and a test?

**Comment by bergundy** [comment]
Addressed in #9
